data<-read.table("household_power_consumption.txt",header = TRUE, sep=";",stringsAsFactors = FALSE)
data2<-subset(data,grepl("^1/2/2007|^2/2/2007",data$Date))
data2[,1]<-as.Date(data2[,1],"%d/%m/%Y")
data2[,3]<-as.numeric(data2[,3])
hist(data2$Global_active_power, col="red", main="Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png")
dev.off()
